language: node_js
node_js:
  - '10.4.1'
jobs:
  include:
    - script: npm run lint
    - script: npm run test
    - stage: npm release
      deploy:
        provider: npm
        email: antonzabolotny@gmail.com
        on:
          branch: master
        api_key:
          secure: njSAX7ATbP1XS9vD0Nuyaz2fGJwfUyK4qhbOtT5cpCEMVw124FeeaoJV1lcQH3OJns9XlpuAKzI8Jmhohiula7hxmMDbXTtK4oCyjW1RdFrX/RkJmyAQphpcnSqH6N7YVytDkBLX2UThbZY3rNl1A1CQJcZAkmCoFeFMB/TRKxrdkKFX1Ox/zGzb+11BeqgkVADiJJjygebJqJMaTzyuFLLFeiI9dV+w7jedlElK70gpCKDK8+kGE9YrJ2RxsqNgcWStOohEI3Sj/dmR2eKMWPk1ZICLgLIc71fPzPyUKD0RSJ/lhF9hqaSvZ9qj2j1h19woosgCwo2/35sSLGiCJEAjZcXx2uoF3ZKV+wHNFeyoqdJmPE7BSTwhpvXyRkLPzxSN9X0tpxbAkrFfi+XIrzIQNzq/ChKKZddG2zOpjZ18Lg2aCC+ns0+p1hcX7Z2WQb8q6VWnY7NFr47r+yVxhjz3PPjTsB/1i6YQ+M6Vz3Fw8Nt/siO0jN/q2s4vy2+R0dapa1/yQ61G+UGRcOsiV49ot2mGVODroA7yK2T60hXW2czM4qjqoW1ZuhrVQx21XF6ocWwvohHXkyNaCcJvHlE/H3dzdolscZJ6oAYEvVhrgjxjZPUWncK+rqj4M5ceIX4aHHKwu5OPp5oa/+loaIplJHfTDlmGqw3S+N7MiOM=
